"""создание Модуля

Revision ID: 46947ebe4897
Revises: 4c3d47172d87
Create Date: 2025-01-19 18:04:43.422810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46947ebe4897'
down_revision: Union[str, None] = '4c3d47172d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sphere_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sphere_id'], ['spheres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('module_id', sa.Integer(), nullable=False))
    op.drop_constraint('courses_sphere_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'modules', ['module_id'], ['id'])
    op.drop_column('courses', 'sphere_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('sphere_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_sphere_id_fkey', 'courses', 'spheres', ['sphere_id'], ['id'])
    op.drop_column('courses', 'module_id')
    op.drop_table('modules')
    # ### end Alembic commands ###
