"""remove_icon_from_modules

Revision ID: 8b62b1244864
Revises: 5c968a863bc7
Create Date: 2025-02-13 22:34:32.027610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b62b1244864'
down_revision: Union[str, None] = '5c968a863bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
