"""создание Модуля

Revision ID: d17df2f9fb74
Revises: 0488a48175ba
Create Date: 2025-01-19 18:34:39.993512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17df2f9fb74'
down_revision: Union[str, None] = '0488a48175ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('modules_user_id_fkey', 'modules', type_='foreignkey')
    op.drop_column('modules', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('modules_user_id_fkey', 'modules', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
